import type { Metadata } from "next";
import "../globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <section className="min-h-full flex flex-col">{children}</section>
  
  );
}
